### ISSUE TITLE
`cogs pull` needs to write TSV or CSV as appropriate

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/cogs#104]
Working with COGS and CSV files today, `cogs pull` was writing the correct `.csv` file names but writing tabs instead of commas.

**Comment by beckyjackson** [comment]
`cogs fetch` stores everything as TSV. If it was originally a CSV file, should it be stored as a CSV in `.cogs/tracked/` or should it just be converted to CSV when we run `cogs pull`? Either way, the user experience would be exactly the same.

**Comment by beckyjackson** [comment]
Side note, I think it would be much easier to implement just converting to CSV when we run `cogs pull`

**Comment by jamesaoverton** [comment]
I'm fine with always using TSV in `.cogs/tracked/` as long as the right format is written with `cogs pull`.
