### ISSUE TITLE
Consider how to ignore a sheet

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/cogs#108]
Currently, if you `cogs add` two tables and then `cogs push`, the Google Sheet will end up with just two sheets, and all other sheets will be deleted. (Note that you can revert changes using Google Sheets history.)

https://github.com/ontodev/cogs/blob/master/cogs/push.py#L215

Now I have a Google Sheet with a bunch of formulas to summarize data on other sheets. COGS doesn't handle formulas, so I can't `cogs add` this sheet. I don't need a local copy of this sheet at all. But I don't want COGS to delete this sheet when I `cogs push`. I'd be happy if COGS just ignored it.

It would be simple enough to provide a list to `clear_remote_sheets` that it would ignore. Then I guess we could use the same list to ignore sheets for `cogs fetch` and `cogs merge` (#102). Maybe we need a new `cogs ignore/unignore` command, or just an `--ignore` option for `cogs add/rm`? And I'm worried that I'm missing other problems, or just making the mental model too complicated.

**Comment by beckyjackson** [comment]
I think `cogs ignore` makes the most sense. Maybe instead of `cogs unignore` we can just do `cogs ignore --revert` or something.

I guess this could go in a config file - something like `.cogs/ignore.tsv`?

**Comment by jamesaoverton** [comment]
Let's try adding an `ignore` column to `.cogs/sheet.tsv` and use `cogs ignore --revert`.

**Comment by jamesaoverton** [comment]
We also need to think about other commands:

- `cogs ls` list ignored sheets?
- `cogs status` no change?

**Comment by jamesaoverton** [comment]
Now that I've tried #110 and had a bit more time to think about it, I'm still not completely clear on the right behaviour.

1. Now I think that we shouldn't (ever?) delete sheets from the Google Sheet. So I guess sheets would be ignored by default, until `cogs add`ed.
2. If sheets are ignored by default, then you would only use `cogs ignore` to stop tracking a sheet that you previously `cogs add`ed (without removing it). Then maybe we don't need `cogs ignore` but just `cogs rm --ignore` option?
3. Now I think that the opposite of `cogs ignore` is `cogs add`.

**Comment by beckyjackson** [comment]
In this case, do we even need an "Ignore" column? If the default behavior is to just ignore any remote sheets that are not in `.cogs/sheet.tsv`, that seems redundant. Can you think of a case where it may be useful?

**Comment by jamesaoverton** [comment]
I was thinking that `.cogs/sheet.tsv` would still have a row for each sheet in the Google Sheet, and then that would still be useful for `cogs ls` or whatever.

**Comment by beckyjackson** [comment]
Gotcha, that makes sense.

I think we can get rid of `cogs ignore`. I don't think I like the `cogs rm --ignore` option because that feels like you're deleting the remote sheet. I would rather do something like:
```
cogs add sheet_title
```

Where usually we require a path (`cogs add PATH`), if the provided title (instead of path) appears as an ignored sheet in `.cogs/sheet.tsv`, we will just stop ignoring it.

**Comment by beckyjackson** [comment]
I updated the PR. New remote sheets are now automatically ignored. You can "unignore" a sheet using `add`. From the docs:

#### Adding an Ignored Sheet

By default, COGS ignores any untracked remote sheets. If you wish to start tracking a new remote sheet, you can do this by passing the sheet title to `add`:

```
cogs add [title]
```

The default path for pulling changes from this newly-added sheet will be the current working directory (the same directory as `.cogs/` is in) and will be a lowercase, space-replaced version of the title (e.g. `My Sheet` becomes `my_sheet.tsv`). If you already have a tracked sheet at this location, the date & time will be appended to the path (e.g., `my_sheet_20200922_103045.tsv` for a sheet fetched at 10:30:45 on 2020/09/22). This path can be updated with [`cogs mv`](#mv).
