### ISSUE TITLE
Implement a `pull` command

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/cogs#11]
The `pull` command will replace tracked local files with their remote copies. The main operation is just to copy corresponding files from `.cogs/` to the local file. But we should:

1. fetch first (I think this is what `git` does?)
2. only overwrite the local file if the remote file is different; if the remote file has not changed, leave the local file alone (we don't want to confuse tools such as `make` by messing with the modification time if the content is the same)

**Comment by beckyjackson** [comment]
What if a new sheet has been added to the remote Google spreadsheet? When we `fetch`, we copy this into the `.cogs/` directory, but do we want to have the users specify a path to store new sheets?

**Comment by jamesaoverton** [comment]
Good question. Maybe we can default to the same directory as `.cogs/`. We would not overwrite an existing file -- we should warn instead, or maybe offer to link them in the `sheet.tsv`.

We should also provide a `mv` command, which will mainly update the `sheet.tsv`.
