### ISSUE TITLE
Make credentials more clear

### ISSUE THREAD

**Issue by beckyjackson** [ontodev/cogs#113]
Currently, creating credentials is buried under `cogs init`. There should be a section at the beginning of the README that provides more details on creating the credentials.

**Comment by turbomam** [comment]
I can do this late this week or early next week.

I got COGS to work on my protected sheets by reading the `init` help and consulting this: https://developers.google.com/sheets/api/guides/authorizing

**Comment by turbomam** [comment]
Or I can do it now

**Comment by beckyjackson** [comment]
Thank you for writing that up @turbomam ! I consolidated some of the details to make it a bit shorter, but your text was a great starting point. Glad you were able to get COGS up and running, please let me know if you have any other questions or run into any problems 😄

**Comment by beckyjackson** [comment]
Resolved by #139
