### ISSUE TITLE
Use the closest COGS project for all operations

### ISSUE THREAD

**Issue by beckyjackson** [ontodev/cogs#116]
If you `cogs init` a new project in the child directory of an existing COGS project, and then perform `cogs push`, the changes will be pushed to the parent COGS project.

COGS operations should always occur on the lowest-level `.cogs` directory found.

**Comment by jamesaoverton** [comment]
I think we're on the same page, but instead of "lowest-level" I would say "closest" directory, I guess, as in "the closest ancestor directory". So COGS should do the minimum amount of climbing necessary to find a `.cogs/` directory.
