### ISSUE TITLE
Implement a special `format.tsv` file

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/cogs#12]
The `.cogs/format.tsv` file will let us track styles and formats for cells -- information that isn't stored in TSV files. This table is just a list of cells that have special formatting or comments.

Rough example:

Sheet | Cell | Format | Comment
------|-----|--------|-------
foo | A2 | error | ID is required

Note: I'm not sure yet what the content of the Format column should be. The two main options are:

1. JSON based on [CellFormat](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/cells#cellformat)
2. Higher-level style names that we can translate back and forth from that JSON, such as "error", "warning".

On `push` COGS should iterate through this file and update formatting for cells. If a cell is not style in `format.tsv`, all formatting should be removed from that cell in the Google Sheet.

On `fetch` COGS should read style information and try to recreate the `format.tsv` file.

The `status` and `diff` commands will also have to compare formats somehow.

**Comment by beckyjackson** [comment]
The `CellFormat` JSON looks pretty complicated... I worry that including that in a cell of a TSV could cause some parsing problems? I'm not sure. I would say we could translate the CellFormat fields to column headers, but there are a lot of them...

The higher-level style names could also be an issue because if a user applies their own style to a cell, it would get lost in translation.

I feel like the easiest thing to do would to be just store a JSON file with all the formatting, but that is different than our current design.

**Comment by jamesaoverton** [comment]
Storing styles in a JSON file makes sense. Maybe a JSON file to store the different style types, assigning each an ID, then the `format.tsv` can use the ID? I'd still like a `format.tsv` that's easy to read and write.

**Comment by beckyjackson** [comment]
The ID could be something like `{sheet}_{cell}.json`, e.g., `foo_A2.json`?

**Comment by jamesaoverton** [comment]
I'm hoping that there's a lot of repetition in the styles. So that could be the name generated when the style is first seen, and then it gets reused.

**Comment by beckyjackson** [comment]
Oh - I see what you're saying. So just a random ID (perhaps random numbers?), but the ID corresponds to the _style_, not necessarily the _cell_.

**Comment by jamesaoverton** [comment]
Yeah, that's what I'd like to try first.

**Comment by beckyjackson** [comment]
I was able to get cell formatting as a dict using the [`gspread-formatting`](https://pypi.org/project/gspread-formatting/) package:

```
{'backgroundColor': {'blue': 1, 'green': 1, 'red': 1},
 'backgroundColorStyle': {'rgbColor': {'blue': 1, 'green': 1, 'red': 1}},
 'horizontalAlignment': 'LEFT',
 'hyperlinkDisplayType': 'PLAIN_TEXT',
 'padding': {'bottom': 2, 'left': 3, 'right': 3, 'top': 2},
 'textFormat': {'bold': False,
                'fontFamily': 'Arial',
                'fontSize': 10,
                'italic': False,
                'strikethrough': False,
                'underline': False},
 'verticalAlignment': 'BOTTOM',
 'wrapStrategy': 'OVERFLOW_CELL'}
```

We can also convert this dict back to a `CellFormat` object using the same module and apply it to the cell in the spreadsheet.

Next question - how do we check that the formatting exists? 

If we have a `.cogs/formats/` folder, then we would have to open each file and compare it to the style we're looking at to see if it exists yet. That seems terribly inefficient if we have lots of styles.

Thinking about this more, I actually want to retract my first comment about the issue with the TSVs. I think it would actually be easier to store the formatting as your original option 1 (assuming we do not use any line breaks):

| Sheet | Cell | Format | Comment |
| --- | --- | --- | --- |
| foo | A2 | {'backgroundColor': {'blue': 0, 'green': 0, 'red': 1}, 'textFormat': {'bold': True}} | ID is required |

Only differences from "default" formatting (which I pasted above) will be stored.

The downside about this method is that we aren't reusing any formats.

**Comment by beckyjackson** [comment]
Another side note - I don't think there's any way to programmatically access "comments" on cells, but you can [annotate them](https://stackoverflow.com/questions/12913874/is-it-possible-to-use-the-google-spreadsheet-api-to-add-a-comment-in-a-cell/56616469#56616469). The annotation is separate from the formatting though, so maybe it would be easier to have a `comment.tsv` file with: Sheet, Cell, Comment.

**Comment by jamesaoverton** [comment]
It sounds like we want annotations, not comments. I would like to reuse styles if at all possible.
