### ISSUE TITLE
Try using Python webbrowser module for `cogs open`

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/cogs#122]
I always wanted `cogs open` to actually open the Google Sheet in a browser (or your Google Sheets App if its installed), but I assumed that was hard to do cross-platform. But when @matentzn asked about it today I looked around and discovered that Python has a [`webbrowser`](https://docs.python.org/3/library/webbrowser.html) module built in!

@beckyjackson Can you play around with this and see if it works?

**Comment by jamesaoverton** [comment]
On macOS this works for me `open "$(cogs open)"`. So if the Python option doesn't work well then we could just add a few examples like this to the README.

**Comment by matentzn** [comment]
`open "$(cogs open)"` totally works and does the trick! :) Thank you!

**Comment by beckyjackson** [comment]
Do we still want to try and do it through python?

**Comment by jamesaoverton** [comment]
Yes please. Not a top priority, but maybe fun?
