### ISSUE TITLE
exceeds grid limits error when sheet name ends with a digit

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/cogs#123]
@srobb1 heroically tracked down this bizarre bug: When a sheet (tab) name ends with a digit, we get a `exceeds grid limits` error:

```
I am trying to use COGS for the first time. I figured out the credentials!!!! Now I am getting errors when I pull that say I am exceeding limits, but the sheet is not bigger than the limits that the error states. But in this particular spreadsheet I have lots and lots of tabs. Any thoughts or ideas?
Traceback (most recent call last):
  File "/home/smr/anaconda3/envs/cogs/bin/cogs", line 8, in <module>
    sys.exit(main())
  File "/home/smr/anaconda3/envs/cogs/lib/python3.9/site-packages/cogs/cli.py", line 249, in main
    args.func(args)
  File "/home/smr/anaconda3/envs/cogs/lib/python3.9/site-packages/cogs/cli.py", line 408, in run_pull
    fetch(verbose=args.verbose)
  File "/home/smr/anaconda3/envs/cogs/lib/python3.9/site-packages/cogs/fetch.py", line 320, in fetch
    cells = get_cell_data(cogs_dir, sheet)
  File "/home/smr/anaconda3/envs/cogs/lib/python3.9/site-packages/cogs/fetch.py", line 113, in get_cell_data
    resp = request.execute()
  File "/home/smr/anaconda3/envs/cogs/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/smr/anaconda3/envs/cogs/lib/python3.9/site-packages/googleapiclient/http.py", line 935, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://sheets.googleapis.com/v4/spreadsheets/1wd-TXKNa7ohufoI_odjNC-xX8VJ9qUk_BDIGxkqHS1Y?ranges=TSA1&fields=sheets%28data%28rowData%28values%28%2A%29%29%29%29&alt=json returned "Range (All_public_bat_genome!TSA1) exceeds grid limits. Max rows: 1015, max columns: 33". Details: "Range (All_public_bat_genome!TSA1) exceeds grid limits. Max rows: 1015, max columns: 33">
```

This points to fetch.py 113 where we're calling the official Google Sheets library. I think that if the name of the sheet ending with a digit is quoted then this will work, but I'm annoyed that they don't do the quoting. We should handle it, either by quoting ourselves or warning loudly about this limitation.

**Comment by jamesaoverton** [comment]
This bug is now officially the front runner for Misleading Error Message of the Year.

**Comment by beckyjackson** [comment]
I'm having some trouble recreating this error. I tried two different things, first adding a sheet with a digit at the end:
```
$ cogs add test1.tsv -t Test1
$ cogs push
```

Then, I added a new "Test2" sheet remotely, and pulled it (after adding the ignored sheet):
```
$ cogs add Test2
$ cogs pull
```

Looking at the error message, it looks like the problem sheet is "All_public_bat_genome" and it's trying to get column `TSA1` which is outside of the limit (TSA corresponds to column 14015). Maybe the sheet got formatted weird and for some reason Sheets thinks there's something in that cell?

**Comment by jamesaoverton** [comment]
"All_public_bat_genome" was the name of the file.

We also found that COGS worked as expected with a single sheet ending with a digit, but failed when we added a second sheet ending with a digit. Can you try that please?

**Comment by srobb1** [comment]
All_public_bat_genomes was the name of the first sheet in that spreadsheet. I started with an existing sheet that I “connect” to. There needs to be more than one sheet. If I just had one sheet with TSA1, it was okay, as soon as I added another, like ACA1 remotely and pulled, I got the error. I removed all the 1s and it worked. I can share a test spreadsheet with you if you like.

**Comment by beckyjackson** [comment]
Yes, if you could share a sheet with me that would be great! My email is
***@***.***

**Comment by srobb1** [comment]
Can you send your email in the obo slack? It is all stared out here. I sent you a direct message in slack.
