### ISSUE TITLE
Implement a `create` command

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/cogs#2]
This comes after `init` #8.

The `create` command should use [`gspread`](https://gspread.readthedocs.io/en/latest/index.html) to create a new Google Sheet.

We'll start with just `gspread.service_account()` for authentication as shown here: https://gspread.readthedocs.io/en/latest/oauth2.html#for-bots-using-service-account

COGS should store the Google Sheet ID in `.cogs/spreadsheet_id.txt`

**Comment by beckyjackson** [comment]
Should `init` create an empty `spreadsheet_id.txt` file? And if we run `init` in a directory that already has a `spreadsheet_id.txt`, does it overwrite it with an empty one or keep the old IDs?

**Comment by jamesaoverton** [comment]
I'd prefer no file, not an empty file. I think that running `init` again should fail with a warning, like git (?).

**Comment by beckyjackson** [comment]
Could we have `sheet.tsv` store the ID, sheet title, and description? Since we can get sheets based on their sheet title?

Then we could have a `table.tsv` or `tab.tsv` with the tab label, description, and path details.

**Comment by jamesaoverton** [comment]
While the terminology isn't consistent, this is the pattern I've seen:

1. sheet / worksheet / table: a grid of rows and columns, corresponding to a single `.tsv` file; I really don't like calling these "tabs" but people sometimes do
2. spreadsheet / workbook: a collection of multiple sheets, corresponding to an `.xlsx` file, Google Sheets "file"

In these issues I've been using `config.tsv` for configuration of (2), and `sheet.tsv` as a list of (1).

We can change our terminology, but I want it to be perfectly consistent. From your comment, I think you're just shifting `sheet.tsv` to `table.tsv` and `config.tsv` to `sheet.tsv`, which I don't think is more clear.

**Comment by jamesaoverton** [comment]
Just to be clear, one `.cogs/` directory will correspond to one Google Sheets "file" with one `spreadsheetId` (i.e. one `gspread` Spreadsheet from `open()`, equivalent to one `.xlsx` file). So it will only make sense to `create` one Google Sheet for it, and I guess there should be an error if you try to `create` when a Google Sheets when we already have a spreadsheetId.

**Comment by beckyjackson** [comment]
Ah - that makes sense. So all the *full* sheet details are in config, and the tabs/tables (which correspond to TSV files) are in `sheet.tsv`.

What does your `config.tsv` look like? Is it just Item name -> value (e.g., `Sheet Name \t Name`)?

**Comment by jamesaoverton** [comment]
Yes, `config.tsv` tab-separated key-value pairs, since I can't think of appropriate headers. All the other TSV files should have headers.

**Comment by beckyjackson** [comment]
Makes sense. I'll rework this.

**Comment by beckyjackson** [comment]
One last question... I'm going to update the PR with these changes, but would it make more sense to specify the title of the sheet and create the sheet during `init`? If each `.cogs` directory corresponds to one Google Sheet, then you'd have to run `init` and `create` once each time anyway.

**Comment by jamesaoverton** [comment]
You're right, I'm not sure anymore if we need `create`.

The only reason I have in favour of `create` is that I think it makes sense to have a corresponding `delete`, which I thought would delete the Google Sheet but not the `.cogs/` directory.

If you think it's better without `create`, I'm happy to try it that way.

**Comment by beckyjackson** [comment]
Hmm... I guess you could still have a `delete` without `create`, which would delete both the `.cogs` directory and the corresponding sheet?

I can see it either way, but I think it makes it a little cleaner to have `init` create the sheet. (I'm not sure if users would be confused as to why you couldn't run `create` multiple times, but we could definitely make that clear in the docs)

**Comment by jamesaoverton** [comment]
Ok, let's do it that way.
