### ISSUE TITLE
Implement an `rm` command

### ISSUE THREAD

**Issue by beckyjackson** [ontodev/cogs#20]
As the opposite of `add` (stop tracking a local table)

**Comment by bjonnh** [comment]
Should it remove the sheet as well?

**Comment by beckyjackson** [comment]
My thought is that it would remove the copy of the sheet in the `.cogs` directory, but leave any local copy alone (specified by the path in `sheet.tsv`).

Also: once you run `cogs push`, it will delete the sheet in the Google spreadsheet.

**Comment by jamesaoverton** [comment]
I agree with @beckyjackson, because this matches the other COGS behaviour. But it is different from `git rm`.

**Comment by bjonnh** [comment]
I'm working on that one.
