### ISSUE TITLE
Implement a `delete` command

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/cogs#3]
This command should read the `.cogs/spreadsheet_id.txt` file created in #2 and delete the Google Sheet with the matching ID. Then it should delete the `.cogs/spreadsheet_id.txt` file.

**Comment by beckyjackson** [comment]
Since we changed `init` to create the sheet as well, I'm thinking that delete should working like this:

1. read `.cogs/config.tsv` to get the Sheet details
2. delete the Google Sheet
3. delete the `.cogs` directory
4. do not touch any local paths specified in `sheet.tsv`

**Comment by jamesaoverton** [comment]
Sounds good.
