### ISSUE TITLE
Convert error table to format/notes

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/cogs#40]
Once we have an output table in the format described here https://github.com/ontodev/robot/issues/712 we should be able to use it in COGS and highlight the problem cells.

**Comment by beckyjackson** [comment]
For running `robot validate`, do we want to have COGS download a ROBOT JAR on `cogs init` and then have a `cogs validate` command that runs `robot validate` and formats the results?

**Comment by jamesaoverton** [comment]
I'm not sure how we should work this, but COGS shouldn't know about ROBOT.

The goal is to have various validation tools, including ROBOT, output these standard error tables, then have COGS use those tables. I would be happy for Make to coordinate most of the work.
