### ISSUE TITLE
Implement a `fetch` command

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/cogs#5]
The `fetch` command will download data from the Google Sheet and store each sheet as a TSV file with matching name in the `.cogs/` directory.

**Comment by beckyjackson** [comment]
Since the `.cogs/` directory gets deleted by `cogs delete`, do we want to instead have the user specify a path to the downloaded TSVs? Or perhaps provide an option in delete to copy the TSVs from `.cogs/` to another directory?

**Comment by jamesaoverton** [comment]
No. Users should `pull` before they `delete`.

**Comment by bjonnh** [comment]
Should it happen only with tracked sheets?
What should happen if the user added a sheet in the googlesheet?

**Comment by jamesaoverton** [comment]
Hmm. I think the `.cogs/` directory should mirror the Google Sheet, and `fetch` should do the mirroring.

**Comment by beckyjackson** [comment]
@bjonnh - are you currently working on this? I'm going to work on some of these issues and I don't want to overlap.

**Comment by bjonnh** [comment]
Nope go ahead.
