### ISSUE TITLE
Consider using GitHub actions for PyPI releases

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/cogs#52]
This is a convenience. While it might be a pain to set up for just one repo, we'll soon have three or four Python repos, and then I think the benefits would be significant.

**Comment by beckyjackson** [comment]
I'd like to get another PyPI release out for COGS. Do you want to do this before our next release?

**Comment by jamesaoverton** [comment]
No rush on this. Go ahead and make the releases you need.

**Comment by beckyjackson** [comment]
It's pretty easy to add GH Actions so I created one. I could test it out and if it fails, I can just make a manual PyPI release? Or we can just wait. Doesn't matter to me.

**Comment by jamesaoverton** [comment]
Sure, try and use the action to make a release.
