### ISSUE TITLE
Consider `connect` command

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/cogs#54]
It would be good to be able to connect to an existing Google Sheet, with something like `cogs connect SHEET_ID`. I think this would:

1. initialize the `.cogs/` directory and `.cogs/config.tsv`
2. ask to Share with the COGS service account and wait. Either:
    A. print an email address for the user to put in the Share dialog
    B. make a Share request, then the sheet owner gets a notification from Google via email
3. fetch and set up the various special tables: sheet, field, format, note

I might be missing something. Right now COGS creates the sheet and is the owner, so this could break some of our assumptions.

**Comment by beckyjackson** [comment]
I think we would want to make the service account the actual owner of the sheet (that should be possible as long as the user approves it). I can't remember the specifics, but I ran into some issues when the service account isn't the owner.
