### ISSUE TITLE
Implement an `add` command

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/cogs#6]
The `add` command will take a TSV file name (e.g. `foo.tsv`) and:

1. add a row to `.cogs/sheet.tsv` for `foo`
2. add the column names `.cogs/field.tsv` if they do not already exist

**Comment by beckyjackson** [comment]
The fields sheet contains: Field, Label, Datatype, Description

If we are just getting the field from the column name, we could only fill in "label". I guess the Field column could be created from a lowercase version of the label with spaces replaced with underscores, but at what point would the datatype and description get filled in?

Sorry if you outlined this somewhere else already - I looked through the other issues and didn't see anything else about `field.tsv`

**Comment by jamesaoverton** [comment]
No, I didn't write up more about this yet. You're already thinking along the same lines as I am:

- Field: a modified version of Label: ASCII, trimmed, lowercase, replace consecutive punctuation with an underscore
- Label: exactly the column name from the TSV
- Datatype: default to "text" for now; later maybe we'll get smarter and try to infer the type based on the column contents or the field name
- Description: blank by default

The trickiest bit is that field definitions are shared across all sheets. So many sheets can have a "label" column, but there will only be one "label" row in `fields.tsv`. Therefore the definition (i.e. type, description) of "label" must be the same across all sheets.
