### ISSUE TITLE
Why does COGS need to own sheets?

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/cogs#61]
It's not terrible, but it's a bit inconvenient that COGS wants to own the sheets that it works on. What are the specific  reasons? What problems does it cause if COGS just has Write permissions?

**Comment by beckyjackson** [comment]
I think #62 answers this - basically, COGS can't do two things without ownership:
1. delete the Spreadsheet
2. transfer the Spreadsheet to a new owner

So for the most part not being an owner is OK.
