### ISSUE TITLE
Consider `clear` command

### ISSUE THREAD

**Issue by beckyjackson** [ontodev/cogs#64]
The `clear` command should take a sheet title and a special keyword (e.g., `data-validation` or something like that). Then, it will clear all "applied" attributes from the sheet. I think the keywords we want to support are:
* formats
* data-validation (or rules?)
* notes

For example: `cogs clear [keyword] -t [sheet-title]` or alternatively `cogs clear -t [sheet-title] -k [keyword]`. I'm not sure which makes more sense.

Let me know if I missed anything.

**Comment by jamesaoverton** [comment]
We could overload `cogs apply` with this functionality, but I like a distinct `cogs clear` better. There should also be an "all" keyword. And it should be possible to clear all sheets.
