### ISSUE TITLE
Implement a `diff` command

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/cogs#9]
The `diff` command will compare each tracked sheet, looking for differences between the cached copy in `.cogs/` and the local file. We'll implement this using [`daff`](https://github.com/paulfitz/daff).

**Comment by beckyjackson** [comment]
`daff`  (plus `tabulate` and `termcolor` for console formatting) seems to work really well for smaller tables:

![image](https://user-images.githubusercontent.com/16750150/86631377-e7924d00-bf82-11ea-8b5c-e964ae60a991.png)

 but for tables with a lot of columns, displaying the changes on the command line is... messy. I tried it on the OBI assay template and it is almost impossible to figure out what's going on:

![image](https://user-images.githubusercontent.com/16750150/86631497-0d1f5680-bf83-11ea-9c89-db21b55eb6d8.png)

`daff` provides an HTML renderer which might actually work better - especially if we're going to be working with templates, I'm just wondering the best way to convey this to the users?

Maybe we have options closer to `robot` than to `git` in this case?

What are your thoughts?
